Update MVEWrapper and test to keras_core
themis-ai/capsa-core pull request #8
Opened 2023-07-19 14:25 UTC by vballoli

2023-07-19 14:32 UTC, vballoli commented
Reference issue: https://github.com/themis-ai/capsa-core/issues/3

2023-07-20 11:51 UTC, egesko requested changes
I left couple of comments, but overall it looks great. Thank you!

2023-07-20 11:51 UTC, egesko commented on capsa/aleatoric/mve.py
>  from ..risk_tensor import RiskTensor
This should cause cause capsa-core to load tensorflow. Any chance you can comment this?

2023-07-20 11:51 UTC, egesko commented on test/test_mve.py
>  import tensorflow_probability as tfp
We should not need `tensorflow_probability` here as well.

2023-07-20 13:17 UTC, vballoli commented on test/test_mve.py
>  import tensorflow_probability as tfp
`tfp` was required for the test data generation. Should we just shift to having them implemented from scratch using the `keras_core.ops` for `MultivariateNormalDiag` (moon data)? (and a small implementation of the quantiles for normal distribution - calib plot )

2023-07-20 13:19 UTC, vballoli commented on capsa/aleatoric/mve.py
>  from ..risk_tensor import RiskTensor
Not sure I got this: tf is not being imported right? so keras_core should ideally load whatever is in the environment variable?

2023-07-21 09:58 UTC, egesko commented on capsa/aleatoric/mve.py
>  from ..risk_tensor import RiskTensor
Oh, my mistake. I read the change incorrectly.

2023-07-21 10:05 UTC, egesko commented on test/test_mve.py
>  import tensorflow_probability as tfp
Yeah, I think that's the best approach. Ideally, we won't to remove all mentions of `tf`,`tfp`. But we can implement that in a different PR.

2023-07-21 10:05 UTC, egesko approved these changes
LGTM! Thank you again!

2023-07-21 10:05 UTC, merged